extends Node

signal boss_progress_updated(current: int, total: int)
signal combat_triggered(module_id: String, enemy_data: Dictionary)
signal combat_ended(result: Dictionary)
signal monster_captured(monster_data: Dictionary)
signal item_obtained(item_id: String, count: int)
signal loop_completed(loop_count: int)
signal tile_placed(module_id: String, grid_index: int)
signal tile_consumed(module_id: String, grid_index: int, remaining_charge: int)
signal tile_disappeared(module_id: String, grid_index: int)
signal boss_spawned(boss_data: Dictionary)
signal game_over(is_victory: bool)
signal game_phase_changed(new_phase: int)
signal turn_started(turn_number: int)
signal turn_ended(turn_number: int)
signal unit_fainted(unit_data: Dictionary)
signal hp_changed(unit_uuid: String, old_hp: int, new_hp: int)
signal status_applied(unit_uuid: String, status: String)
signal skill_used(user_uuid: String, skill_id: String, target_uuid: String)
signal command_executed(command_data: Dictionary)
